#ifndef header_h
#define header_h

String file1=
"<!DOCTYPE html>\r\n"
"<html lang=en>\r\n"
"<meta name=viewport content=\"width=device-width, initial-scale=1\">\r\n"
"<head>\r\n"
"<title>lemonSW recovery</title>\r\n"
"<style>.footer{position:fixed;bottom:0;text-align:center;width:100%;display:block}h1{text-shadow:2px 1.5px red;font-family:\"Georgia\",Times,serif;margin:5%;margin-bottom:60px;text-align:center}body{font:normal 18px/1.5 \"Fira Sans\",\"Helvetica Neue\",sans-serif;background-color:#2b3e4c;color:#fff;padding-left:0;padding-top:100px}.container{width:80%;max-width:1200px;margin:0 auto}.container *{box-sizing:border-box}.flex-outer,.flex-inner{list-style-type:none;padding:0}.flex-outer{max-width:800px;margin:0 auto}.flex-outer li,.flex-inner{display:flex;flex-wrap:wrap;align-items:center}.flex-inner{padding:0 8px;justify-content:space-between}.flex-outer>li:not(:last-child){margin-bottom:20px}.flex-outer li label,.flex-outer li p{padding:8px;font-weight:300;letter-spacing:.09em;text-transform:uppercase}.flex-outer>li>label,.flex-outer li p{flex:1 0 120px;max-width:220px}.flex-outer>li>label+*,.flex-inner{flex:1 0 220px}.flex-outer li p{margin:0}.flex-outer li input:not([type='checkbox']),.flex-outer li textarea{padding:15px;border:0}.flex-outer li button{margin-left:auto;padding:8px 16px;border:0;background:red;color:#f2f2f2;text-transform:uppercase;letter-spacing:.09em;border-radius:2px}button{margin-left:auto;padding:8px 16px;border:0;background:red;color:#f2f2f2;text-transform:uppercase;letter-spacing:.09em;border-radius:2px}.flex-inner li{width:100px}@media screen and (max-width:600px){.col-25,.col-75,input[type=submit]{width:100%;margin-top:0}}.custom-select{position:relative}.custom-select select{display:none}.select-selected{background-color:#fff;color:#000}.select-selected:after{position:absolute;content:\"\";top:14px;right:10px;width:0;height:0;border:6px solid transparent;border-color:#000 transparent transparent transparent}.select-selected.select-arrow-active:after{border-color:transparent transparent #000 transparent;top:7px}.select-items div,.select-selected{color:#000;padding:8px 16px;border:1px solid transparent;border-color:transparent transparent rgba(0,0,0,0.1) transparent;cursor:pointer;user-select:none}.select-items{flex:1 0 120px;max-width:800px;position:absolute;background-color:#fff;top:100%;left:0;right:0;z-index:99}.select-hide{display:none}.select-items div:hover,.same-as-selected{background-color:rgba(0,0,0,0.1)}.container2{width:auto;margin:-50px 0 60px -35px}.progressbar{counter-reset:step}.progressbar li{list-style-type:none;width:33.3%;float:left;font-size:12px;position:relative;text-align:center;text-transform:uppercase;color:#7d7d7d}.progressbar li:before{width:30px;height:30px;content:counter(step);counter-increment:step;line-height:30px;border:2px solid #7d7d7d;display:block;text-align:center;margin:0 auto 10px auto;border-radius:50%;background-color:white}.progressbar li:after{width:100%;height:2px;content:'';position:absolute;background-color:#7d7d7d;top:15px;left:-50%;z-index:-1}.progressbar li:first-child:after{content:none}.progressbar li.active{color:green}.progressbar li.active:before{border-color:#55b776}.progressbar li.active+li:after{background-color:#55b776}.switch{position:relative;display:inline-block;width:60px;height:34px}.switch input{display:none}.slider{position:absolute;cursor:pointer;top:0;left:0;right:0;bottom:0;background-color:#7d7d7d;-webkit-transition:.4s;transition:.4s}.slider:before{position:absolute;content:\"\";height:26px;width:26px;left:4px;bottom:4px;background-color:white;-webkit-transition:.4s;transition:.4s}input:checked+.slider{background-color:#000}input:focus+.slider{box-shadow:0 0 1px #000}input:checked+.slider:before{-webkit-transform:translateX(26px);-ms-transform:translateX(26px);transform:translateX(26px)}form{padding-top:40px}.slider.round{border-radius:34px}.slider.round:before{border-radius:50%}.custom-box{display:block;position:relative;padding-left:35px;margin-bottom:12px;cursor:pointer;font-size:22px;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}.custom-box input{position:absolute;opacity:0;cursor:pointer;height:0;width:0}.checkmark{position:absolute;top:0;left:0;height:25px;width:25px;background-color:#eee}.custom-box:hover input~.checkmark{background-color:#ccc}.custom-box input:checked~.checkmark{background-color:#2196f3}.checkmark:after{content:\"\";position:absolute;display:none}.custom-box input:checked~.checkmark:after{display:block}.custom-box .checkmark:after{left:9px;top:5px;width:5px;height:10px;border:solid white;border-width:0 3px 3px 0;-webkit-transform:rotate(45deg);-ms-transform:rotate(45deg);transform:rotate(45deg)}</style>\r\n"
"</head>\r\n"
"<body>\r\n"
"<div class=container2>\r\n"
"<ul class=progressbar>\r\n"
"<li id=1 class=active>WiFi</li>\r\n"
"<li id=2>Account</li>\r\n"
"<li id=3>Options</li>\r\n"
"</ul>\r\n"
"</div>\r\n"
"<br>\r\n"
"<h1 id=scanning>Scanning...<br></h1>\r\n"
"<h1 id=error>Something went wrong while communicating with the board...<br></h1>\r\n"
"<div id=connecting>\r\n"
"<h1>Connecting... <br></h1>\r\n"
"<center>(Your computer can disconnect from the WiFi. Don't close the page and check your computer's connected)\r\n"
"</center><br><br>\r\n"
"</div>\r\n"
"<div id=timeout>\r\n"
"<h1>It is taking too long to connect... <br></h1>\r\n"
"<center>(You can still wait as the board keeps trying to connect, but password may be wrong)</center><br>\r\n"
"</div>\r\n"
"<h1 id=connectingMq>Connecting... <br></h1>\r\n"
"<h1 id=connected><br></h1>\r\n"
"<form id=wifi>\r\n"
"<ul class=\"flex-outer container\">\r\n"
"<li id=select>\r\n"
"<label>SSID:</label>\r\n"
"<div class=custom-select>\r\n"
"<select id=ssidWifi>\r\n"
"</select>\r\n"
"</div>\r\n"
"</li>\r\n"
"<li id=custom>\r\n"
"<label>Hiden SSID:</label>\r\n"
"<input id=customWifi type=text name=# value placeholder>\r\n"
"</li>\r\n"
"<li>\r\n"
"<label>Password:</label>\r\n"
"<input id=pwWifi type=text name=# value placeholder>\r\n"
"</li>\r\n"
"<li>\r\n"
"<button type=button onclick=connect()>Connect</button>\r\n"
"</li>\r\n"
"</ul>\r\n"
"</form>\r\n"
"<form id=mq>\r\n"
"<ul class=\"flex-outer container\">\r\n"
"<li>\r\n"
"<label>Username:</label>\r\n"
"<input id=userMq type=text name=# value placeholder>\r\n"
"</li>\r\n"
"<li>\r\n"
"<label>Password:</label>\r\n"
"<input id=pwMq type=password name=# value placeholder>\r\n"
"</li>\r\n"
"<li>\r\n"
"<button type=button onclick=connectMq()>Connect</button>\r\n"
"</li>\r\n"
"</ul>\r\n"
"<br>\r\n"
"</form>\r\n"
"<div id=options>\r\n"
"<form>\r\n"
"<ul class=\"flex-outer container\">\r\n"
"<li>\r\n"
"<label>Enable static IP:</label>\r\n"
"<label class=custom-box style=max-width:25px>\r\n"
"<input type=checkbox id=static>\r\n"
"<span class=checkmark onclick=\"toggle('staticForm')\"></span>\r\n"
"</label>\r\n"
"</li>\r\n"
"</ul>\r\n"
"<ul class=\"flex-outer container\" id=staticForm>\r\n"
"<li>\r\n"
"<label>IP:</label>\r\n"
"<input id=ip type=text name=# value placeholder>\r\n"
"</li>\r\n"
"<li>\r\n"
"<label>Gateway:</label>\r\n"
"<input id=gateway type=text name=# value placeholder>\r\n"
"</li>\r\n"
"<li>\r\n"
"<label>Netmask:</label>\r\n"
"<input id=netmask type=text name=# value placeholder>\r\n"
"</li>\r\n"
"<li>\r\n"
"<label>DNS:</label>\r\n"
"<input id=dns type=text name=# value placeholder>\r\n"
"</li>\r\n"
"</ul>\r\n"
"<br>\r\n"
"</form>\r\n"
"<form>\r\n"
"<ul class=\"flex-outer container\">\r\n"
"<li>\r\n"
"<label>Enable local dashboard (disables server connection):</label>\r\n"
"<label class=custom-box style=max-width:25px>\r\n"
"<input type=checkbox id=local>\r\n"
"<span class=checkmark></span>\r\n"
"</label>\r\n"
"</li>\r\n"
"</ul>\r\n"
"</form>\r\n"
"<br>\r\n"
"<br>\r\n"
"</div>\r\n"
"<button id=back type=button onclick=\"if(step>1){step=step-1;}progress()\">Previous</button>\r\n"
"<div style=float:right;text-align:right>\r\n"
"<button id=save type=button onclick=save()>Save</button>\r\n"
"</div>\r\n"
"<div style=float:right;text-align:right;margin-top:15px>\r\n"
"<button id=next type=button onclick=\"step=step+1;progress()\">Next</button>\r\n"
"</div>\r\n"
"<div style=float:right;text-align:right;margin-top:15px>\r\n"
"<button id=skip type=button onclick=\"step=step+1;progress()\">Skip</button>\r\n"
"</div>\r\n"
"</body>\r\n"
"<script>function show(id){var object=document.getElementById(id);object.removeAttribute(\"style\");}\r\n"
"function hide(id){var object=document.getElementById(id);object.style.display='none';}\r\n"
"function toggle(id){var object=document.getElementById(id);if(object.style.display=='none'){object.removeAttribute(\"style\");}else{object.style.display='none';}}\r\n"
"function req(url,callback,type){let r=new XMLHttpRequest();r.open('GET',url,true);if(type!==undefined){r.responseType=type;}else{r.responseType='text';}\r\n"
"r.onreadystatechange=function(){if(r.readyState==4){callback(r.status,r.response);}}.bind(this);r.send();}\r\n"
"function hideall(){var e=[\"error\",\"connecting\",\"timeout\",\"wifi\",\"save\",\"next\",\"back\",\"connected\",\"scanning\",\"mq\",\"connectingMq\",\"skip\",\"options\"];for(var i=0;i<e.length;i++){hide(e[i]);}}\r\n"
"var step=1;var timeout=0;hideall();scan();check();function scan(){show(\"scanning\");req('http://192.168.1.1/scan',function(status,response){if(status===200||status===204){var x=document.getElementById(\"ssidWifi\");if(status===200){var ssid=Object.keys(response);for(var i=0;i<ssid.length;i++){var option=document.createElement(\"option\");option.text=ssid[i]+' (Signal: '+response[ssid[i]]+')';option.id=ssid[i];x.add(option);}}\r\n"
"var option=document.createElement(\"option\");option.text='Custom wifi...';option.id=\"\";x.add(option);list();hide(\"scanning\");hide(\"custom\");show(\"wifi\");}else{hideall();show(\"error\");return;}},'json');}\r\n"
"function custom(){var e=document.getElementById('ssidWifi');if(e.options[e.selectedIndex].id!==\"\"){hide(\"custom\");}else{show(\"custom\");}}\r\n"
"function connect(){hideall();show(\"connecting\");var ssid=document.getElementById('ssidWifi');var pw=document.getElementById('pwWifi');var custom=document.getElementById('customWifi');if(ssid.options[ssid.selectedIndex].id!==\"\"){var url='http://192.168.1.1/test?ssid='+ssid.options[ssid.selectedIndex].id+'&pw='+pw.value;}else{var url='http://192.168.1.1/test?ssid='+custom.value+'&pw='+pw.value;}\r\n"
"req(url,function(status,response){if(status===200){timeout=(new Date()).getTime();check();}else{console.log(\"Something went wrong while communicating with the board...\");}});}\r\n"
"function check(){req('http://192.168.1.1/check',function(status,response){if(status===200){if(response==\".\"){timeout++;show(\"connecting\");if(((new Date()).getTime()-timeout)>25000){show(\"timeout\");hide(\"connecting\");}\r\n"
"check();}else{hide(\"connecting\");document.getElementById(\"connected\").innerHTML=\"Connected to: \"+response\r\n"
"show(\"connected\");show(\"next\");}}else if(status!==204){alert(\"Reconnect to the WiFi before continuing...\");check();}});}\r\n"
"function progress(){hideall();var one=document.getElementById('1');var two=document.getElementById('2');var three=document.getElementById('3');if(step===1){one.classList.add(\"active\");two.classList.remove(\"active\");three.classList.remove(\"active\");location.reload();}else if(step===2){one.classList.add(\"active\");two.classList.add(\"active\");three.classList.remove(\"active\");show(\"mq\");show(\"back\");show(\"skip\");}else if(step===3){one.classList.add(\"active\");two.classList.add(\"active\");three.classList.add(\"active\");show(\"options\");show(\"back\");show(\"save\");hide(\"staticForm\");}}\r\n"
"function connectMq(){var mq_user=document.getElementById('userMq').value;var mq_pw=document.getElementById('pwMq').value;var url=\"http://192.168.1.1/mqtt?user=\"+mq_user+\"&pw=\"+mq_pw;hideall();show(\"connectingMq\");req(url,function(status,response){if(status===200){hide(\"connectingMq\");show(\"mq\");show(\"back\");show(\"skip\");var s=Number(response);if(s===9){alert(\"Wrong user or password\");}else if(s<0){alert(\"Can't reach server, please check WiFi\");}else if(s===0){alert(\"Connected!\");step=3;progress();}else{alert(\"Something went wrong :(\");}}else{hideall();show(\"error\");show(\"back\");}});}\r\n"
"function save(){var static=document.getElementById(\"static\").checked;var local=document.getElementById(\"local\").checked;var url='http://192.168.1.1/save';if(static){url=url+'?static=1';var ip=document.getElementById(\"ip\").value;var gateway=document.getElementById(\"gateway\").value;var netmask=document.getElementById(\"netmask\").value;var dns=document.getElementById(\"dns\").value;var r=/^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/;if(!(r.test(ip)&&r.test(gateway)&&r.test(netmask)&&r.test(dns))){alert(\"Invalid values! Did you entered correct IP, netmask, gateway or DNS?\")\r\n"
"return;}\r\n"
"url=url+'&ip='+ip;url=url+'&gateway='+gateway;url=url+'&netmask='+netmask;url=url+'&dns='+dns;}else{url=url+'?static=0&ip=&gateway=&netmask=&dns=';}\r\n"
"if(local){url=url+'&local=1';}else{url=url+'&local=0';}\r\n"
"req(url,function(status,response){if(status===200){window.location.replace(\"http://192.168.1.1/reboot\");}else{alert(\"Something went wrong\");}});}</script>\r\n"
"<script>function list(){var x,i,j,selElmnt,a,b,c;x=document.getElementsByClassName(\"custom-select\");for(i=0;i<x.length;i++){selElmnt=x[i].getElementsByTagName(\"select\")[0];a=document.createElement(\"DIV\");a.setAttribute(\"class\",\"select-selected\");a.innerHTML=selElmnt.options[selElmnt.selectedIndex].innerHTML;x[i].appendChild(a);b=document.createElement(\"DIV\");b.setAttribute(\"class\",\"select-items select-hide\");for(j=0;j<selElmnt.length;j++){c=document.createElement(\"DIV\");c.innerHTML=selElmnt.options[j].innerHTML;c.addEventListener(\"click\",function(e){var y,i,k,s,h;s=this.parentNode.parentNode.getElementsByTagName(\"select\")[0];h=this.parentNode.previousSibling;for(i=0;i<s.length;i++){if(s.options[i].innerHTML==this.innerHTML){s.selectedIndex=i;h.innerHTML=this.innerHTML;y=this.parentNode.getElementsByClassName(\"same-as-selected\");for(k=0;k<y.length;k++){y[k].removeAttribute(\"class\");}\r\n"
"this.setAttribute(\"class\",\"same-as-selected\");break;}}\r\n"
"h.click();});b.appendChild(c);}\r\n"
"x[i].appendChild(b);a.addEventListener(\"click\",function(e){e.stopPropagation();closeAllSelect(this);this.nextSibling.classList.toggle(\"select-hide\");this.classList.toggle(\"select-arrow-active\");});}\r\n"
"document.addEventListener(\"click\",closeAllSelect);}\r\n"
"function closeAllSelect(elmnt){var x,y,i,arrNo=[];x=document.getElementsByClassName(\"select-items\");y=document.getElementsByClassName(\"select-selected\");for(i=0;i<y.length;i++){if(elmnt==y[i]){arrNo.push(i)}else{y[i].classList.remove(\"select-arrow-active\");}}\r\n"
"for(i=0;i<x.length;i++){if(arrNo.indexOf(i)){x[i].classList.add(\"select-hide\");}}\r\n"
"custom();}</script>\r\n"
"</html>\r\n";

#endif